FROM python:3.12-alpine

WORKDIR /usr/src/app

COPY ./backend/poetry.lock ./backend/pyproject.toml ./

RUN apk update \
    apk add --no-cache \
    build-base \
    curl
        
ENV PATH="/root/.local/bin:$PATH"

RUN pip3 install poetry

RUN poetry config virtualenvs.create false

RUN poetry install --no-root

COPY ./backend/backend .

EXPOSE 5000

CMD [ "gunicorn", "--bind", "0.0.0.0:5000", "--timeout", "1200", "wsgi:app" ]