FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY ./frontend/package-lock.json ./frontend/package.json ./frontend/tsconfig.json ./frontend/tsconfig.node.json ./

RUN npm install
        
COPY ./frontend .

RUN npm run build

EXPOSE 8080

CMD [ "npm", "run", "preview" ]