name: Backend Build Check

on:
    push:
        branches:
            - main

jobs:
    Backend-Build-Check:
        name: Checks if the backend successfully builds or not.
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Setup python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            - name: Run image (Poetry setup)
              uses: abatilo/actions-poetry@v2
              with:
                poetry-version: "1.7.1"
            - name: Install Dependencies
              run: cd backend/backend && poetry install
            - name: Build Project
              run: cd backend/backend && poetry run python3 main.py
    