name: Build and Deploy to DockerHub

on:
    push:
        branches:
            - main

jobs:
    build-and-push-frontend:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Create containers
          run: docker build -t fmj-backend -f docker/Dockerfile.backend . 

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and Push Backend
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/fmj-backend:latest
            context: .
            file: docker/Dockerfile.backend


